version: "3.8"

services:
  planify-backoffice:
    image: kreyzix/planify-backoffice:${VERSION}
    build: .
    ports:
      - 3000:3000
    restart: always
    environment:
      - REACT_APP_SERVER_URL=${REACT_APP_SERVER_URL}
      - REACT_APP_GOOGLE_MAPS_KEY= ${REACT_APP_GOOGLE_MAPS_KEY}
      - REACT_APP_IMAGE_PLACEHOLDER= ${REACT_APP_IMAGE_PLACEHOLDER}
      - REACT_APP_USER_AVATAR_PLACEHOLDER= ${REACT_APP_USER_AVATAR_PLACEHOLDER}
      - REACT_APP_PRIMARY_COLOR= ${REACT_APP_PRIMARY_COLOR}
      - REACT_APP_PRIMARY_LIGHTER_COLOR= ${REACT_APP_PRIMARY_LIGHTER_COLOR}
