---
- hosts: server
  tasks:
    - name: install pip3
      apt: name=python3-pip state=present 
      
    - name: Install Docker  Module for Python
      pip:
        name:
          - docker
          - docker-compose

    - name: Pull code from github
      ansible.builtin.git:
        repo: "git@github.com:jrivo/planify-backoffice.git"
        dest: ~/planify-backoffice
        version: "{{ BRANCH }}"
        clone: true
        update: true

    - name: Pull and run new image
      become: true
      community.docker.docker_compose:
        project_src: ~/planify-backoffice
        state: present
        pull: true
      environment:
        REACT_APP_SERVER_URL: "{{ REACT_APP_SERVER_URL }}"
        REACT_APP_GOOGLE_MAPS_KEY: "{{ REACT_APP_GOOGLE_MAPS_KEY }}"
        REACT_APP_PRIMARY_COLOR: "{{ REACT_APP_PRIMARY_COLOR }}"
        REACT_APP_USER_AVATAR_PLACEHOLDER: "{{ REACT_APP_USER_AVATAR_PLACEHOLDER }}"
        REACT_APP_PRIMARY_LIGHTER_COLOR: "{{ REACT_APP_PRIMARY_LIGHTER_COLOR }}"
        REACT_APP_IMAGE_PLACEHOLDER: "{{ REACT_APP_IMAGE_PLACEHOLDER }}"
        VERSION: "{{ NEW_VERSION }}"

